name: repore_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.6.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  gap: ^3.0.1
  auto_route: ^7.8.3
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
