// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QTz-Kh_gXZCGmkEzSM9400Xei62JoA0',
    appId: '1:730467495650:web:ca252c63b3c07dc71778bb',
    messagingSenderId: '730467495650',
    projectId: 'repore-chat',
    authDomain: 'repore-chat.firebaseapp.com',
    storageBucket: 'repore-chat.firebasestorage.app',
    measurementId: 'G-C1R1NHMPFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-UOygW5LcIWzGCgb7lJGpy3EA35QTPg',
    appId: '1:730467495650:android:af3a3b87738f0ae41778bb',
    messagingSenderId: '730467495650',
    projectId: 'repore-chat',
    storageBucket: 'repore-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL34g5ZgY0o1i8EzxS3kvnCvdyte9xPZI',
    appId: '1:730467495650:ios:10e1c7d578c9eba01778bb',
    messagingSenderId: '730467495650',
    projectId: 'repore-chat',
    storageBucket: 'repore-chat.firebasestorage.app',
    iosBundleId: 'com.example.reporeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL34g5ZgY0o1i8EzxS3kvnCvdyte9xPZI',
    appId: '1:730467495650:ios:10e1c7d578c9eba01778bb',
    messagingSenderId: '730467495650',
    projectId: 'repore-chat',
    storageBucket: 'repore-chat.firebasestorage.app',
    iosBundleId: 'com.example.reporeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4QTz-Kh_gXZCGmkEzSM9400Xei62JoA0',
    appId: '1:730467495650:web:b58032dc82aed6e51778bb',
    messagingSenderId: '730467495650',
    projectId: 'repore-chat',
    authDomain: 'repore-chat.firebaseapp.com',
    storageBucket: 'repore-chat.firebasestorage.app',
    measurementId: 'G-NDMZGNVM37',
  );
}
